---

- hosts: test
  gather_facts: no
  become: yes
  tasks:
    - name: Create User
      user:
        name: user1
        state: present
        createhome: yes
    - name: Create ssh directory
      file:
        path: /home/user1/.ssh
        state: directory
        mode: '0700'
        owner: user1
    - name: Generate ssh-key
      user:
        name: user1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/user1/.ssh/id_rsa   

    - name: Add ssh key to authorize_key
      copy: 
        src: /home/user1/.ssh/id_rsa.pub
        dest: /home/user1/.ssh/authorize_key
        owner: user1
        mode: '0600'
 
