---
# tasks file for php-fpm
- name: install php
  package:
    name: php
    state: present
- name: install php-fpm
  package:
    name: php-fpm
    state: present
- name: upload www.conf file
  copy:
    src: "{{ php-fpm_config_file_source }}"
    dest: "{{ php-fpm_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
